version: "3.1"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=upload_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"